apiVersion: v1
kind: Service
metadata:
  name: ip-capture-api
spec:
  selector:
    app: ip-capture-api  # Match the label of the Flask app
  ports:
    - protocol: TCP
      port: 3000        # Port inside the Kubernetes cluster
      targetPort: 3000  # Port on the Flask container
  type: LoadBalancer    # Expose it externally using LoadBalancer
